-- Seed staff members for the gift card POS system.
-- Run this after schema.sql (or after M003 migration on existing databases).
--
-- PINs are stored as bcrypt hashes (cost 10) — never plaintext.
-- Generate a hash first:
--   node scripts/hash-pin.mjs 1234
-- Then paste the output below.
--
-- To deactivate a staff member (invalidates their session immediately):
--   UPDATE staff SET active = FALSE WHERE name = 'Jim';
--
-- To change a PIN (also immediately invalidates their current session):
--   1. node scripts/hash-pin.mjs new-pin
--   2. UPDATE staff SET pin_hash = '<output>' WHERE name = 'Jim';
--
-- To see all staff:
--   SELECT id, name, active, created_at FROM staff ORDER BY created_at;

-- ── Add your barbers below ───────────────────────────────────────────────────

-- INSERT INTO staff (name, pin_hash) VALUES ('Jim', '<bcrypt hash from hash-pin.mjs>');
